---
title: "Cover Letter"
author: "Denis Ostroushko"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Dear Hiring Manager,

I am writing to express my strong interest in the Biostatistician position with the Cancer Survivorship and Benign Hematology Research Program. As a data analyst with three years of experience in a healthcare insurance company, I have gained invaluable experience working with large and complex claims and enrollment data. In my previous role, I have used both SAS and R to perform data analysis and have developed a strong proficiency in analysis design and statistical modeling.

I am particularly passionate about the application of statistics for inference, especially when it comes to formulating new knowledge about human health. I strongly believe that data analysis can help us identify new factors that improve health outcomes, particularly for oncology patients, and create new ways of creating personalized treatments. I am confident that my skills and experience can help the research program in achieving these objectives.

While pursuing my MS in biostatistics, which I expect to receive by May 2024, I have honed my skills in utilizing online resources to learn new skills quickly. I am very curious and bring new ways of looking at the data to my team leaders without hesitation. Additionally, with the right guidance and environment, I am confident that I can harness new skills quickly and effectively.

As someone who is committed to contributing to the research activities of the University of Minnesota’s Childhood Cancer Survivor Program, I am excited about the opportunity to serve as the resident expert in complex data resources. I believe that my passion for data analysis, statistical modeling, and health research, combined with my strong communication and collaboration skills, would make me an excellent addition to your team.

Thank you for considering my application. I am looking forward to the opportunity to further discuss my qualifications and interest in the position.

Sincerely, Denis Ostroushko




